spring.application.name=backend
server.port=8081

app.auth.email=admin@paf.com
app.auth.password=Admin@123
app.auth.name=My Account
app.auth.role=ADMIN

app.mail.from=${APP_MAIL_FROM:ominduayoda@gmail.com}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${APP_MAIL_USERNAME:${APP_MAIL_FROM:ominduayoda@gmail.com}}
spring.mail.password=${APP_MAIL_PASSWORD:buszcmjsvafkqnto}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
